flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonUI.java

FlatButtonUI.getPreferredSize throw exception when button.getComponentCount()>0.
In that case we should return null as same way of BasicButtonUI.

FlatButtonUI getPreferredSize nullPointer fix

---

flatlaf-intellij-themes/src/main/java/com/formdev/flatlaf/intellijthemes/materialthemeuilite/Utils.java

Using flatlaf intellijthemes as a dependency does not work for all themes from the subfolder 'material-theme-ui-lite' because of the usage of ".." to  to load the resource.

Fix relative resource location

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPopupFactory.java

Linux adds drop shadow to heavy weight popups. So there is no
need to draw shadow manually.

Fix popup shadow issue on Linux

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPopupFactory.java

When using dark theme on light platform theme, there was a
background flashing effect on popups.
See #94

Fix menu background flashing effect

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatSystemProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/Animator.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd

This PR adds scrolling tabs with mouse wheel or trackpad (if mouse is over tabs area).
The two arrow buttons are now larger and do repeat scrolling as long as pressed.
This is first part of TabbedPane improvements as discussed in issue #40.
CC @smileatom @Chrriis

TabbedPane wheel scrolling

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/JavaCompatibility.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/resources/Bundle.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/resources/Bundle_de.properties
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR replaces forward/backward scrolling arrow buttons with a "Show Hidden Tabs" button.
If pressed, it shows a popup menu that contains (partly) hidden tabs and selecting one activates that tab.
Leading and trailing hidden tabs are separated with a line in the popup menu.
Custom tab components (set with `JTabbedPane.setTabComponentAt(int index, Component component)`)
are **not** used in the popup menu. So make sure that the tab title is also set.
If you prefer forward/backward buttons, use 
~~~java
UIManager.put( "TabbedPane.hiddenTabsNavigation", "arrowButtons" );
~~~
It is also possible to specify hiddenTabsNavigation type per tabbedpane via client property:
~~~java
myTabbedPane.putClientProperty( "JTabbedPane.hiddenTabsNavigation", "moreTabsButton" );
or …

Tabbedpane "Show Hidden Tabs" button

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd

This PR introduces support for adding custom components to left and right sides of tabs area.
Set client properties `JTabbedPane.leadingComponent` or `JTabbedPane.trailingComponent` on a `JTabbedPane` to add components:
~~~java
myTabbedPane.putClientProperty( "JTabbedPane.leadingComponent", new JButton( "Hello" ) );
myTabbedPane.putClientProperty( "JTabbedPane.trailingComponent", new JButton( "World" ) );
~~~
The preferred width of the added components is used, but the height is always set to the tab height.
Use an additional panel if your component should have a smaller height.
At the moment there is no gap between the leading/trailing components and the tabs.
I'm undecided whether FlatLaf should add a gap or the leading/trailing components should do (if necessary).
This is part of …

TabbedPane custom components on left and right sides of tabs area

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/icons/FlatTabbedPaneCloseIcon.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/TriStateCheckBox.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd
flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/FlatTestLaf.properties
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR introduces support for closable tabs.
Set client property `JTabbedPane.tabClosable` to `true` on a `JTabbedPane` to enable closing tabs.
You also have to provide a callback in client property `JTabbedPane.tabCloseCallback` that is responsible for closing the tab.
~~~java
myTabbedPane.putClientProperty( "JTabbedPane.tabClosable", true );
myTabbedPane.putClientProperty( "JTabbedPane.tabCloseCallback",
(java.util.function.BiConsumer<JTabbedPane, Integer>) (tabbedPane, tabIndex) -> {
// close tab here
tabbedPane.removeTabAt( tabIndex );
} );
~~~
If you do not need the tabbed pane in the callback, it is possible to use a `java.util.function.IntConsumer`:
~~~java
myTabbedPane.putClientProperty( "JTabbedPane.tabCloseCallback",
(java.util.function.IntConsumer) tabIndex -> {
// close tab …

TabbedPane closable tabs

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd
flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/FlatTestLaf.properties
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

By default the tab area is aligned to the left edge. 
Now you can also align it to the right, center or fill.
To use this for the whole application (allowed values are `leading`, `trailing`, `center` and `fill`:
~~~java
UIManager.put( "TabbedPane.tabAreaAlignment", "center" );
~~~
To use this for single tabbed pane:
~~~java
myTabbedPane.putClientProperty( "JTabbedPane.tabAreaAlignment", "center" );
~~~
With this PR you can now specify minimum and maximum tab widths.
This is useful for IDE like applications where you e.g. use file names in tab titles.
With minimum tab width you can avoid small tabs for short file names.
With maximum tab width you can avoid too wide tabs for long file names.
Minimum tab width makes tabs wider:
Maximum tab width makes tabs smaller:
~~~java …

TabbedPane: tab area alignment; min/max tab widths; tab icon placement; tab width mode

---

flatlaf-core/src/main/java/com/formdev/flatlaf/icons/FlatAnimatedIcon.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/AnimatedIcon.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/ColorFunctions.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/CubicBezierEasing.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatAnimatedIconTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatAnimatedIconTest.jfd

This PR adds interface [AnimatedIcon](https://github.com/JFormDesigner/FlatLaf/blob/1293e2a07488977df27bbd3bfff68c88a9bded44/flatlaf-core/src/main/java/com/formdev/flatlaf/util/AnimatedIcon.java) (extends `javax.swing.Icon`)
that automatically animates painting on component value changes.
The cool thing is that the animation is done in the icon and it is not necessary to change anything in the UI delegates.
This is not yet used, but intended for future animates (issue #66).
The test application [FlatAnimatedIconTest](https://github.com/JFormDesigner/FlatLaf/blob/1293e2a07488977df27bbd3bfff68c88a9bded44/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatAnimatedIconTest.java) includes (experimental) animated icons
for radio buttons, toggle switches and a minimal example:
Same as …

AnimatedIcon

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTextFieldUI.java

Hey,
we added a custom icon to a textfield and used additional inset to do so. Since left and top inset is already being honored, we thought it'd make sense to do the same with the right inset.
However, there's two questions:
1. How do correctly format the source code (We used IDEA which should use .editorconfig, right?)
2. Should we clip the placeholder or use an ellipsis (Currently we are clipping it)

TextField Placeholder now honors the right inset

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java

This font should be used for UI elements since macOS 10.15.
See https://youtrack.jetbrains.com/issue/JBR-1915 for more information.
Other JREs, including JetBrains Runtime 8 do not handle kerning for that font correctly.

JetBrains Runtime 11 has support for displaying the .AppleSystemUIFont font.

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java

Sub-pixel anti-aliasing (VALUE_TEXT_ANTIALIAS_LCD_HRGB) causes font rendering with too much weight with a JetBrains JREs (both 8 and 11). This can be seen when comparing the text rendering of UI elements between IntelliJ IDEA and FlatLaf.
This commits aligns FlatLaf's behavior with IntelliJ IDEA which disables sub-pixel anti-aliasing on macOS for its IDE anti-aliasing setting and uses greyscale anti-aliasing by default (see com.intellij.ide.ui.AntialiasingType.canUseSubpixelAAForIDE).
Before:
After:

Switched from sub-pixel to greyscale text anti-aliasing on macOS when running with a JetBrains JRE

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableHeaderUI.java

To implement FlatLaf UIs for CellStyleTableHeaderUI and SortableTableHeaderUI from the Jide Grids library, access to the paintColumnBorders method is required.

Made paintColumnBorders protected to help with implementing derived table header UIs

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeWindowBorder.java

This makes it possible to support situations where the extraction of a DLL at runtime is not possible.
Rationale:
Extracting DLLs to the temporary directory will trigger some anti-virus tools and can lead to quarantined binaries.
This is why in install4j we use the RegisterNatives JNI function to provide native code from the installer executable without loading an additional library. For the native code in FlatLaf, we would like to do the same.

Add a setter for the native provider

---

flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java

The menu items for custom window decorations and embeded menu bar aren't selected anymore if the feature isn't supported.
On top of that, there's now a tooltip indicating that these aren't supported.
Regarding the previous condition for enabling the item:
```java
supportsWindowDecorations && !JBRCustomDecorations.isSupported()
```
I deem it very confusing that we set the item to `enabled` if `JBRCustomDecorations` isn't supported.
Would you mind explaining this? I'd like to add an explanatory comment in the code here.

Fix selected states for native window border related menu items

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonUI.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatButton.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponentsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponentsTest.jfd

To create buttons that look like toolbar buttons but have a focus indicator.
This behavior can be achieved with JideButton, but it would be preferable to use FlatButton instead.

Added ButtonType.borderLess

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatDesktopPaneUI.java

When a custom `DesktopManager` was installed, the FlatLaf one will not be used (so no small content snapshot for iconified frames will be present).
This patch allows a custom `DesktopManager` to keep the FlatLaf iconified feature.
My solution is to wrap the old `DesktopManager` in a container class so only the `iconifyFrame` methods is overriden.

Fixed JInternalFrame iconified content snapshot for already installed DesktopManager

---

flatlaf-jide-oss/src/main/java/com/formdev/flatlaf/jideoss/ui/FlatJidePainter.java
flatlaf-jide-oss/src/main/java/com/formdev/flatlaf/jideoss/ui/FlatJideTabbedPaneUI.java
flatlaf-jide-oss/src/main/resources/com/formdev/flatlaf/jideoss/FlatLaf.properties
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/JIDE-FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/JIDE-FlatLightLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/jideoss/FlatJideOssContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/jideoss/FlatJideOssContainerTest.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR updates the look of `JideTabbedPane` to match `JTabbedPane`, adds tab separators and fixes some issues.
List of improvements:
- new scroll and list buttons
- new tab close buttons
- support tab separators
- support selected tab background
- scale tab gripper
- fixed disabled tab text, which was unreadable in dark themes
- fixed tab icon and title locations in vertical tabs
- tab layout fixes for compact resize mode
- fixed location of tab title editing box
- hide tab selection and tab area separator for `tabbedPane.setHideOneTab(true)` if tabbed pane contains only one tab
Enable for all tabbed panes in application (`JideTabbedPane` and `JTabbedPane`) with:
~~~java
UIManager.put( "TabbedPane.showTabSeparators", true );
~~~
Or for single tabbed pane with:
~~~java …

JideTabbedPane improvements

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatCaret.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatFormattedTextFieldUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPasswordFieldUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTextFieldUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/BasicComponentsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/BasicComponentsPanel.jfd
flatlaf-demo/src/main/resources/com/formdev/flatlaf/demo/icons/DataTables.svg
flatlaf-demo/src/main/resources/com/formdev/flatlaf/demo/icons/bookmarkGroup.svg
flatlaf-demo/src/main/resources/com/formdev/flatlaf/demo/icons/user.svg
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatFormattedTextField.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatPasswordField.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatTextField.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR adds support for leading and trailing icons to text fields (and subclasses).
You can use any icon/image that implements interface `javax.swing.Icon`.
The optimal icon height is 16px (unscaled).
The usage is very simple. E.g.:
~~~java
myTextField.putClientProperty( "JTextField.leadingIcon", new FlatSearchIcon() );
myTextField.putClientProperty( "JTextField.trailingIcon", new FlatSVGIcon( "com/myapp/icons/myIcon.svg" ) );
~~~
If you use bitmap icons (PNG or GIF) and support Java 8, then consider using `ScaledImageIcon` (package `com.formdev.flatlaf.util`) to scale your icon up on HiDPI screens.
~~~java
myTextField.putClientProperty( "JTextField.leadingIcon",
new ScaledImageIcon( new ImageIcon( getClass().getResource( "/com/myapp/icons/myIcon.png" ) ) ) );
~~~
Note that the icons are …

TextField: leading and trailing icons

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/FlatLafDemo.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/TabsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/TabsPanel.jfd
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatTabbedPane.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0_202.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0_202.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This pull request adds a new option to tabbed panes that changes how their active tab and content separator is painted.
It makes the content separator wrap around the active tab much like many typical tabbed pane designs (like metal laf).
- It looks good and it's a widespread design that I've personally been missing in flatlaf. Aside from being present in most UI frameworks on desktop, it can also be found in flat web UI's made with react for example.
- Generally, this design makes the active tab (and whole tabbed pane) pop out / visible a lot more. 
I feel like the current flatlaf material design-ish tabs tend to be hard to find in certain situations/UIs. After all the only indicator of a tabbed pane at first sight (aside from content of the tabs themselves) is just the tiny selection …

New tabbed pane active tab border painting style

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuItemRenderer.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatMenusTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatMenusTest.jfd

I'd like to suggest this change to paint a different icon when a menu item is highlighted. The idea is to provide an alternative icon that has a better contrast with the selection background. This behavior can be seen for example on some menus of IntelliJ where the icons are painted with a different shade of gray when an item is selected:
**Open icon not selected (color #6E6E6E)**
**Open icon selected (color #AFB1B3)**

MenuItem: paint the selected icon when the item is selected

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/icons/FlatRevealIcon.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPasswordFieldUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTextFieldUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/BasicComponentsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/BasicComponentsPanel.jfd
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatUIDefaultsInspector.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatUIDefaultsInspector.jfd
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatFormattedTextField.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatPasswordField.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatTextField.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.jfd
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatFindReplaceBar.java
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatFindReplaceBar.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

Text fields now can have a clear button that empties the text field:
The button is only visible if the text field is not empty, editable and enabled.
To enable the clear button either set a client property:
~~~java
textField.putClientProperty( "JTextField.showClearButton", true );
~~~
Or use styling:
~~~java
textField.putClientProperty( "FlatLaf.style", "showClearButton: true" );
~~~
By default the text field is emptied (`setText("")`) if the clear button is pressed.
If you need special action, e.g. cancel a search operation, you can specify a callback via client property:
~~~java
myTextField.putClientProperty( "JTextField.clearCallback",
(Runnable) () -> {
// clear field here or cancel search
} );
}
~~~
Or if you need the text field in the callback use :
~~~java …

TextField clear button and PasswordField reveal password button

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatSystemProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatWindowsNativeWindowBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/NativeLibrary.java

Added the system property flatlaf.nativeLibraryPath to specify a directory where the native libraries have been extracted.
Avoiding extraction at runtime to the temporary directory is useful in order to prevent anti-virus software from blocking the library loading.

Add a system property to load pre-extracted native libraries from a directory

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java
flatlaf-core/src/main/java/com/formdev/flatlaf/SubMenuUsabilityHelper.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatSubMenusTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatSubMenusTest.jfd

This PR improves the usability of submenus (see issue #247).
It makes it much easier to move the mouse into a submenu without the risk that the submenu is hidden.
Without this PR, you have to move the mouse on the **red** path, otherwise the submenu will be hidden.
With this PR, you can move the mouse on the **green** path, over other menu items.
The implementation uses a **safe triangle**, described in [this article](https://height.app/blog/guide-to-build-context-menus#safe-triangle).
When you move the mouse within the safe triangle toward the submenu, it stays open.
Demo:
To see the safe triangle in your application (for testing) use:
~~~java
UIManager.put( "FlatLaf.debug.menu.showSafeTriangle", true );
~~~
To disable this feature use:
~~~java
UIManager.put( "Menu.useSafeTriangle", …

Menus: improved usability of submenus

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatFileChooserUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/SystemInfo.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatChooserTest.java
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR adds a shortcuts panel to the left side of all file choosers (class `JFileChooser`):
On Windows, the content of the shortcuts panel is the same as in the Java Windows L&F.
On macOS and Linux the shortcuts panel is empty and hidden.
However you can customize the content. E.g.
~~~java
UIManager.put( "FileChooser.shortcuts.filesFunction", (Function<File[], File[]>) files -> {
ArrayList<File> list = new ArrayList<>( Arrays.asList( files ) );
list.add( 0, new File( System.getProperty( "user.home" ) ) );
return list.toArray( new File[list.size()] );
} );
UIManager.put( "FileChooser.shortcuts.displayNameFunction", (Function<File, String>) file -> {
if( file.getAbsolutePath().equals( System.getProperty( "user.home" ) ) )
return "Home";
return null;
} );
UIManager.put( …

File chooser shortcuts panel

---

flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatInspector.java

Currently there isn't a good way to get rid of the mouse listener the inspector adds. Alternatively the mouse listener could be added/removed in `setEnabled`, in which case `uninstall` could go away entirely.

FlatInspector: add/remove mouse listener in setEnabled

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatToolBarUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/MoreComponentsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/MoreComponentsPanel.jfd
flatlaf-extras/src/main/resources/com/formdev/flatlaf/extras/resources/DerivedColorKeys.properties
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponentsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponentsTest.jfd
flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/FlatTestLaf.properties
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatThemePreviewAll.java
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatThemePreviewAll.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR adds a hover effect to button groups (`javax.swing.ButtonGroup`) in toolbars.
If mouse is over a button then all buttons in same button group are highlighted
and the user easily sees which buttons belong to hovered button.
Example from the FlatLaf Demo app:

ToolBar: hover effect for button groups

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuBarUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuItemRenderer.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/FlatTestLaf.properties
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR enables using "rounded" selection for menu items.
It also enables using different selection colors for top-level `JMenu`s.
This is not yet used in any theme, but intended to be used
for macOS themes (see PR #533) and future Windows 11 style themes.
Perhaps this should also be used for existing themes to make menus look more beautiful.
Any opinions?
(left image shows rounded selection; right image shows default look)
UI properties for above screenshot (see [Application properties files](https://www.formdev.com/flatlaf/how-to-customize/#application_properties)):
~~~properties
@menuItemMargin = 3,9,3,9
MenuBar.selectionBackground = darken(@menuBackground,15%,derived)
MenuBar.selectionForeground = @foreground
MenuBar.selectionInsets = 1,0,1,0
MenuBar.selectionEmbeddedInsets = 3,0,3,0 …

Menus: rounded selection

---

.gitignore
flatlaf-core/build.gradle.kts
flatlaf-core/src/main/java/com/formdev/flatlaf/themes/FlatMacDarkLaf.java
flatlaf-core/src/main/java/com/formdev/flatlaf/themes/FlatMacLightLaf.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatArrowButton.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatComboBoxUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatSpinnerUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatUIUtils.java
flatlaf-core/src/main/module-info/module-info.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/themes/FlatMacDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/themes/FlatMacLightLaf.properties
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/intellijthemes/IJThemesPanel.java
flatlaf-extras/src/main/resources/com/formdev/flatlaf/extras/resources/DerivedColorKeys.properties
flatlaf-jide-oss/src/main/java/com/formdev/flatlaf/jideoss/ui/FlatJideSplitButtonUI.java
flatlaf-jide-oss/src/main/java/com/formdev/flatlaf/jideoss/ui/FlatJideTabbedPaneUI.java
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/misc/MacOSColorDump.playground/Contents.swift
flatlaf-testing/misc/MacOSColorDump.playground/contents.xcplayground
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatPaintingTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/uidefaults/UIDefaultsDump.java
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatThemePreviewAll.java
flatlaf-theme-editor/src/main/java/com/formdev/flatlaf/themeeditor/FlatThemePreviewAll.jfd

This PR adds macOS light and dark themes that use macOS Monterey (v12.2) colors and style.
The intention was to create themes that **look similar** to native macOS applications.
The popup of not editable combo boxes is positioned similar to native macOS `NSPopUpButton` controls:
Known issues:
- changing accent color not yet supported
- tabbed pane style not macOS like
- selection in lists, tables, trees and menu items do not have round corners
To try it out, download the build artifacts from here: https://github.com/JFormDesigner/FlatLaf/actions/runs/2319472414
The new look and feel class names are:
- `com.formdev.flatlaf.themes.FlatMacLightLaf`
- `com.formdev.flatlaf.themes.FlatMacDarkLaf`

macOS light and dark themes

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

For whatever reason, Swing's `JTree` shows closed/opened/leaf icons on all rows.
Other components like `JList` or `JTable` do not show such icons.
Modern applications do not show such icons in trees.
So this PR removes those closed/opened/leaf icons from trees:
Note that icons set in custom tree cell renderers are still displayed. This PR affects only the default closed/opened/leaf icons.
If you prefer the old behavior use:
~~~properties
UIManager.put( "Tree.showDefaultIcons", true );
~~~

Tree: hide default closed/opened/leaf icons by default

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatRoundBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatSpinnerUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/themes/FlatMacDarkLaf.properties
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTextComponentsTest.jfd

This is a supplement for PR #533.
This PR makes the spinner component in macOS themes look more similar to native macOS stepper.
Old:
New:
Native macOS stepper:
(screenshot from Xcode > Preferences > Text Editing > Display > Line wrapping)

macOS themes: make spinner look like macOS stepper

---

flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatRootPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatNativeWindowBorderTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatWindowDecorationsTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatWindowDecorationsTest.jfd

(work in progress)
Purpose of this PR is to improve customizing of title bar in FlatLaf window decorations (usually used on Windows 10/11).
- hide window title, iconify, maximize and close buttons
- hide window icon (since FlatLaf 2.0)
- change title bar background/foreground (since FlatLaf 1.1.2)
- fullWindowContent option (similar to macOS https://www.formdev.com/flatlaf/macos/#full_window_content)
- optionally place iconify, maximize and close buttons on left side (in reverse order), useful if fullWindowContent is enabled
- specify areas where the user can click-and-drag window (if fullWindowContent is enabled)
- TBD
~~~java
frameOrDialog.getRootPane().putClientProperty( FlatClientProperties.TITLE_BAR_SHOW_ICON, false );
frameOrDialog.getRootPane().putClientProperty( …

Window decorations: Title bar customizing

---

flatlaf-core/src/main/java/com/formdev/flatlaf/util/ScaledImageIcon.java

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because "image" is null
at com.formdev.flatlaf.util.ScaledImageIcon.paintIcon(ScaledImageIcon.java:103)
at java.desktop/javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:191)
at com.formdev.flatlaf.ui.FlatLabelUI.paint(FlatLabelUI.java:254)
at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
at …

catch ScaledImageIcon npe

---

flatlaf-extras/README.md
flatlaf-extras/build.gradle.kts
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGIcon.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGUtils.java
flatlaf-extras/src/main/module-info/module-info.java
gradle/libs.versions.toml

Replace svgSalamander with jsvg

---

CHANGELOG.md
flatlaf-core/build.gradle.kts
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeLibrary.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatWindowsNativeWindowBorder.java
flatlaf-natives/flatlaf-natives-windows/build.gradle.kts

Closes #443
This PR adds native library support for Windows on ARM.
Verification steps
1. Compile native libraries and build flatlaf-demo.
2. Observe embedded menu bars working on all Windows architectures (i.e., x86, x86_64, _and_ aarch64).

Windows on ARM Support

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatFileChooserUI.java

Related: #403
The fix for [JDK-8277299](https://bugs.openjdk.org/browse/JDK-8277299) was backported to Java 17.0.3 (with https://github.com/openjdk/jdk17u-dev/pull/98) and using system icons in later subversions should not cause a crash. Thus, this PR amends the version range for disabling system icons.

x86: Narrow version range for not using system icons

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPopupFactory.java

Fixing NPE when showing a popup without an invoker on Windows 10

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollPaneBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollPaneUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableValue.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-testing/dumps/uidefaults/FlatDarculaLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatIntelliJLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatRoundedScrollPaneTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatRoundedScrollPaneTest.jfd
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTestFrame.java
flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/FlatTestLaf.properties
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This is an attempt to bring rounded border to `JScrollPane` and all component that are usually placed into a scrollpane. E.g. `JTextArea`, `JTextPane`, `JEditorPane`, `JList`, `JTree` and `JTable`.
The problem is that there are multiple overlapping components involved:
- the `JScrollPane,` which has the border
- the `JViewport,` which has the view component as child (e.g. a `JList`)
- optional column and row headers
- optional corner components
- vertical and horizontal `JScrollBar`s
They are painted in this order and using rounded border on scrollpane would look like this:
The viewport/list and the scrollbar simply paint over the rounded corners.
And there is no way to fix this for the viewport in the look and feel.
(maybe a custom scrollpane implementation, that paints its border and …

Scrollpane rounded border

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableValue.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/ScrollablePanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/TabsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/TabsPanel.jfd
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatTabbedPane.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatContainerTest.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR brings rotated/vertical tabs to TabbedPane.
There is a new UI property that controls rotation for **all** tabbed panes in application:
~~~properties
TabbedPane.tabRotation = none
~~~
- `none` does not rotate (the default)
- `auto` rotates left if tab placement is left, rotates right if tab placement is right, does not rotate if tab placement is top or bottom
- `left` always rotates to the left for all tab placements
- `right` always rotates to the right for all tab placements
To rotate a **single** tabbed pane, use client property `JTabbedPane.tabRotation`:
~~~java
tabbedPane.putClientProperty( "JTabbedPane.tabRotation", "left" );
~~~

TabbedPane: support rotated/vertical tabs

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableHeaderUI.java

The table header background is never restored after hover when the label renderer is opaque. 
Here's a demo video:
https://github.com/JFormDesigner/FlatLaf/assets/55930104/3c154be6-f2b3-439c-bab9-c893eb865505
Cheers,
Dar
--

Table header background is never restored after hover when the renderer background is null

---

README.md

Hi! Recently, our open-source Minecraft mod-making toolkit [MCreator updated its LAF to FlatLaf](https://github.com/MCreator/MCreator/pull/4683). I hope this is the right way to add software to the readme list :)
Two screenshots of your amazing LAF in action in our software:

Request to add MCreator to list of apps using FlatLAF

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatListUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableCellBorder.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatUIUtils.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableValue.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DataComponentsPanel.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DataComponentsPanel.jfd
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.jfd

This PR enables using "rounded" selection for table selection.
This is not yet used in any theme, but intended to be used in the future.
UI properties for above screenshot (see [Application properties files](https://www.formdev.com/flatlaf/how-to-customize/#application_properties)):
~~~properties
Table.selectionArc = 6
Table.selectionInsets = 0,1,0,1
~~~
UI properties for above screenshot:
~~~properties
Table.selectionArc = 6
~~~
UI properties for above screenshot:
~~~properties
Table.selectionArc = 6
Table.selectionInsets = 0,1,0,1
~~~

Table: rounded selection

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatComboBoxUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatEditorPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatLabelUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatListUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPanelUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPasswordFieldUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatProgressBarUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatRadioButtonUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollBarUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatScrollPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatSeparatorUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatSliderUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatSpinnerUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatStylingSupport.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableHeaderUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTextFieldUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatToggleButtonUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatToolBarSeparatorUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatToolBarUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatUIUtils.java
flatlaf-core/src/main/java/com/formdev/flatlaf/util/HiDPIUtils.java
flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/FlatLafDemo.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatHiDPITest.java

There is a problem in Swing, when using scale factors that end on .25 or .75
(e.g. 1.25, 1.75, 2.25, etc) and repainting single components.
Sometimes, under special conditions, the right and/or bottom 1px edge of the component is not repainted.
Following screenshot shows examples where the right and/or bottom 1px edge of a component was not repainted:
This PR introduces new repaint methods that fix/workaround the issue:
~~~java
HiDPIUtils.repaint( Component c );
HiDPIUtils.repaint( Component c, Rectangle r );
HiDPIUtils.repaint( Component c, int x, int y, int width, int height );
~~~
fixes issues #860 and #582
There is also a [repaint manager](https://docs.oracle.com/javase%2F8%2Fdocs%2Fapi%2F%2F/javax/swing/RepaintManager.html), that also fixes/workarounds the issue,
but does not need …

HiDPI: fix incomplete component repainting at 125% or 175% scaling on Windows

---

flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableValue.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

Allow settings a custom alternate row color in JTree.  See: https://github.com/JFormDesigner/FlatLaf/issues/900
Cheers,
Dar
--

Support for alternate row color in JTree

---

CHANGELOG.md
flatlaf-core/src/main/java/com/formdev/flatlaf/FlatClientProperties.java
flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTreeUI.java
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableInfo.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyleableValue.java
flatlaf-core/src/test/java/com/formdev/flatlaf/ui/TestFlatStyling.java
flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/components/FlatTree.java
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.java
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponents2Test.jfd
flatlaf-theme-editor/src/main/resources/com/formdev/flatlaf/themeeditor/FlatLafUIKeys.txt

This PR adds support for wide tree cell renderers, which occupy (nearly) full width of tree.
Left screenshot shows bounds of wide cells renderers (red rectangles).
Right screenshot shows default (non-wide) cell bounds.
This gives you more flexibility and you can use whole row width to show some extra information. (see issue #922)
E.g. an icon for some rows:
For a single tree:
~~~java
tree.putClientProperty( FlatClientProperties.TREE_WIDE_CELL_RENDERER, true );
~~~
For all trees in app use properties file:
~~~properties
Tree.wideCellRenderer = true
~~~

Tree: support wide cell renderer

---

CHANGELOG.md
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/themes/FlatMacDarkLaf.properties
flatlaf-core/src/main/resources/com/formdev/flatlaf/themes/FlatMacLightLaf.properties
flatlaf-testing/dumps/uidefaults/FlatDarculaLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatIntelliJLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacDarkLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatMacLightLaf_1.8.0.txt
flatlaf-testing/dumps/uidefaults/FlatTestLaf_1.8.0.txt
flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/uidefaults/UIDefaultsDump.java

This PR increases contrast of text for better readability: (issue #762)
- In **FlatLaf Dark**, **FlatLaf Darcula** and many dark IntelliJ themes made all text colors brighter.
- In **FlatLaf Light**, **FlatLaf IntelliJ** and many light IntelliJ themes made disabled text colors slightly darker.
- In **FlatLaf macOS Light** made disabled text colors darker.
- In **FlatLaf macOS Dark** made text colors of "default" button and selected ToggleButton lighter.
**FlatLaf Dark** theme (left is old, right is new):
**FlatLaf Light** theme with slightly (only 5%) darker **disabled text** colors (left is old, right is new):
**FlatLaf macOS Light** theme with darker **disabled text** colors (left is old, right is new):
**FlatLaf macOS Dark** theme with lighter text in "default" button (left is old, …

Increase contrast of text for better readability
